spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: jdbc:mariadb://localhost:3306/anjeonRe
    driver-class-name: org.mariadb.jdbc.Driver
    username: tatayeon  # RDS MariaDB ????
    password: 1234  # RDS MariaDB ????
  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: create  # RDS?? ??? ?? ????
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
    show-sql: true

jwt:
  secret: SpqowieudsddsrsakldjfhyTKkgx213nH213dsadDsadsDSadsASDSAasdsaTRYYUJYDSJHasdjksahdsdlkjgfh
  expiration_time: 2592000000 # 30?

django:
  api:
    url: "http://localhost:8000/api/upload/"

springdoc:
  swagger-ui:
    path: /api-test

#server:
#  port: 8080
#  ssl:
#    enabled: true
#    key-store: arn:aws:acm:ap-northeast-2:891376917825:certificate/f4b701fc-8d9a-47f8-8fea-24fa6e19b8d1  # ??? ?? (p12 ?? jks)
#    key-store-password: your-password
#    key-store-type: PKCS12
